config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'about/feedback'
  post 'about/feedback'
  get 'about', to: 'about#index'
  get 'about/feeds'
  get 'about/help'
  get 'about/changelog'
  get 'about/queries'

  root 'index#index'

  # Catch all old pgo feeds
  get 'feed(/*stuff)', to: 'about#legacy', defaults: { format: 'atom' }

  resources :categories, only: %i[index show search]

  resources :packages, only: [:index, :show, :search], constraints: { id: /[^.]*/ } do
    collection do
      get 'search'
      get 'suggest'
      get 'resolve'

      get 'added'
      get 'updated'
      get 'stable'
      get 'keyworded'
    end

    member do
      get 'changelog'
    end
  end

  resources :useflags do
    collection do
      get 'popular'
      get 'search'
      get 'suggest'
    end
  end

  resources :arches do
    member do
      get 'stable'
      get 'keyworded'
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{@title} – " if @title %>Gentoo Packages</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="theme-color" content="#54487a">
  <meta name="description" content="<%= "#{@description} in the " if @description %>Gentoo Packages Database">
  <%= stylesheet_pack_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <% if content_for? :head -%>
    <%= yield :head %>
  <% end -%>
</head>
<body class="kk">
<header>
  <div class="site-title">
    <div class="container">
      <div class="row justify-content-between">
        <div class="logo">
          <a href="/" title="Back to the homepage" class="site-logo">
            <img src="https://assets.gentoo.org/tyrian/site-logo.png" alt="Gentoo" srcset="https://assets.gentoo.org/tyrian/site-logo.svg">
          </a>
          <span class="site-label">Packages</span>
        </div>
        <div class="site-title-buttons">
          <div class="btn-group btn-group-sm">
            <a href="https://get.gentoo.org/" role="button" class="btn get-gentoo"><span class="fa fa-fw fa-download"></span> <strong>Get Gentoo!</strong></a>
            <div class="btn-group btn-group-sm">
              <a class="btn gentoo-org-sites dropdown-toggle" data-toggle="dropdown" data-target="#" href="#">
                <span class="fa fa-fw fa-map-o"></span> <span class="d-none d-sm-inline">gentoo.org sites</span> <span class="caret"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="https://www.gentoo.org/" title="Main Gentoo website"><span class="fa fa-home fa-fw"></span> gentoo.org</a>
                <a class="dropdown-item" href="https://wiki.gentoo.org/" title="Find and contribute documentation"><span class="fa fa-file-text-o fa-fw"></span> Wiki</a>
                <a class="dropdown-item" href="https://bugs.gentoo.org/" title="Report issues and find common issues"><span class="fa fa-bug fa-fw"></span> Bugs</a>
                <a class="dropdown-item" href="https://forums.gentoo.org/" title="Discuss with the community"><span class="fa fa-comments-o fa-fw"></span> Forums</a>
                <a class="dropdown-item" href="https://packages.gentoo.org/" title="Find software for your Gentoo"><span class="fa fa-hdd-o fa-fw"></span> Packages</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="https://planet.gentoo.org/" title="Find out what's going on in the developer community"><span class="fa fa-rss fa-fw"></span> Planet</a>
                <a class="dropdown-item" href="https://archives.gentoo.org/" title="Read up on past discussions"><span class="fa fa-archive fa-fw"></span> Archives</a>
                <a class="dropdown-item" href="https://sources.gentoo.org/" title="Browse our source code"><span class="fa fa-code fa-fw"></span> Sources</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="https://infra-status.gentoo.org/" title="Get updates on the services provided by Gentoo"><span class="fa fa-server fa-fw"></span> Infra Status</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <nav class="tyrian-navbar navbar navbar-dark navbar-expand-lg bg-primary" role="navigation">
    <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse navbar-main-collapse" id="navbar-main-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if @nav == :index %>"><%= link_to t(:home), '/', class: "nav-link" %></li>
            <li class="nav-item <%= 'active' if @nav == :packages %>"><%= link_to t(:packages), categories_path, class: "nav-link" %></li>
            <li class="nav-item <%= 'active' if @nav == :use %>"><%= link_to t(:use_flags), useflags_path, class: "nav-link" %></li>
            <li class="nav-item <%= 'active' if @nav == :arches %>"><%= link_to t(:architectures), arches_path, class: "nav-link" %></li>
            <li class="nav-item <%= 'active' if @nav == :about %>"><%= link_to t(:about), about_path, class: "nav-link" %></li>

          </ul>

          <% unless @nav == :index %>
            <form class="form-inline inlinesearch" role="search" action="<%= search_packages_path %>" method="get">

              <div class="input-group">

                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1"><i class="fa fa-search" aria-hidden="true"></i></span>
                </div>

                <input class="form-control" type="text" name="q" type="text" placeholder="Find Packages" aria-label="Find Packages">
              </div>

            </form>
          <% end %>

        </div>
    </div>
  </nav>
</header>

<%= yield :header %>

<div class="container mb-5">
  <div class="row">
    <div class="col-12">
      <%= yield %>
    </div>
  </div>
</div>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-12 offset-md-2 col-md-7">
        <h3 class="footerhead"><%= t :app_name %></h3>
        <div class="row">
          <div class="col-xs-12 col-md-4">
            <span class="kk-group-header"><%= t :data_current_as_of %></span><br><%= last_import_start ? i18n_date(last_import_start) : 'unknown' %>
          </div>
          <div class="col-xs-12 col-md-4">
          </div>
          <div class="col-xs-12 col-md-4">
          </div>
        </div>
      </div>
      <div class="col-12 col-md-3">
        <h3 class="footerhead">Questions or comments?</h3>
        Please feel free to <a href="https://www.gentoo.org/inside-gentoo/contact/">contact us</a>.
        <p class="mt-2"><%= `git describe --tags` %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-2 col-sm-3 col-md-2">
        <ul class="footerlinks three-icons">
          <li><a href="https://twitter.com/gentoo" title="@Gentoo on Twitter"><span class="fa fa-twitter fa-fw"></span></a></li>
          <li><a href="https://www.facebook.com/gentoo.org" title="Gentoo on Facebook"><span class="fa fa-facebook fa-fw"></span></a></li>
          <li><a href="https://www.reddit.com/r/Gentoo/" title="Gentoo on Reddit"><span class="fa fa-reddit-alien fa-fw"></span></a></li>
        </ul>
      </div>
      <div class="col-10 col-sm-9 col-md-10">
        <strong>&copy; 2001&ndash;2020 Gentoo Foundation, Inc.</strong><br>
        <small>
          Gentoo is a trademark of the Gentoo Foundation, Inc.
          The contents of this document, unless otherwise expressly stated, are licensed under the
          <a href="https://creativecommons.org/licenses/by-sa/3.0/" rel="license">CC-BY-SA-3.0</a> license.
          The <a href="https://www.gentoo.org/inside-gentoo/foundation/name-logo-guidelines.html">Gentoo Name and Logo Usage Guidelines</a> apply.
        </small>
      </div>
    </div>
  </div>
</footer>
</body>
</html>